language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install .
  - pip install coveralls
script:
  - ./test --coverage
  - coverage run -m py.test
after_success:
  - coveralls
