language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
install:
  - pip install .
script: 
  - ./test
deploy:
    provider: pypi
    user: messenger
    on:
        tags: true


