language: python
install:
  - pip install .
  - pip install coveralls hypothesis
script:
  - ./test --coverage
  - coverage run -m py.test
after_success:
  - coveralls
jobs:
  include:
    - python: 2.7
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9
    - python: 3.10-dev
    - python: nightly
  allow_failures:
    - python: 3.10-dev
    - python: nightly
  fast_finish: true
