#!/bin/csh -f

set nonomatch

# the rest is common to all python directories
rm -f *.pyc *.pyo .test*.sum expected result install.out
rm -rf build *.egg-info dist __pycache__ .coverage .coverage-html htmlcov
rm -f .*.log
rm -rf **/{__pycache__,*.pyc}
rm -rf tests/htmlcov
