#!/usr/bin/env python3

# Run module self tests
#
# To run with default python version use: ./test
# To run with python2 use               : python2 test
# To run with python3 use               : python3 test

from runtests import runTests
import sys

if sys.version_info < (3,):
    # unicode issues result in tests failing on Python2
    raise SystemExit

runTests(['inform', 'doctests'])
