#!/bin/sh

rm -rf ~/.local/lib/python*/site-packages/inform*

echo "#################"
echo "Python2 tests ..."
echo "#################"
pip2 install --user ..
# python2.7 -m pytest -xvv
python2.7 -m pytest -v

rm -rf ~/.local/lib/python*/site-packages/inform*

echo
echo "#################"
echo "Python3 tests ..."
echo "#################"
pip3 install --user ..
# python3.6 -m pytest -xvv
python3 -m pytest -v
